### ISSUE TITLE
support `--jvm`?

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#21]
[TiL](https://contributors.scala-lang.org/t/easier-scala-installation/4326/3?u=sethtisue) you can:

```
cs launch --jvm 11 scala
```

maybe scala-runners could/should allow it as well

**Comment by dwijnand** [comment]
You can pass anything you want directly to coursier (cs) with `-C`, so `scala -C--jvm=11`.

Given that, I don't think there's need to have this as a top-level option, WDYT?

**Comment by SethTisue** [comment]
Hmm, not sure what I think. If we think of the users of `scala` as primarily `scala` users who aren't necessarily aware of what Coursier is, then those users might find it strange and hard to remember which flags they're supposed to prepend `-C` to and which, not.

Whereas to someone who's already familiar with and a user of courier, the current design might seem more natural.

Have you thought about passing any unrecognized flags directly to Coursier, so then users would never need `-C`?

**Comment by lrytz** [comment]
What happens when you pass `-C--jvm` you're not using coursier to manage your jvms? I think making it a top-level option would be too confusing. Or the top-level option could check if the system does use coursier for managing the jvm, and fail otherwise.

**Comment by dwijnand** [comment]
> What happens when you pass `-C--jvm` you're not using coursier to manage your jvms?

It starts downloading AdoptOpenJDK (I quickly Ctrl-C'd that).

> those users might find it strange and hard to remember which flags they're supposed to prepend `-C` to and which, not.

Yeah, but I feel like it's better to build less and expose composable bits, instead of "magic-ing it away"... ✨  In this case, I don't quite understand why `--jvm 11` is so needed.

> Have you thought about passing any unrecognized flags directly to Coursier, so then users would never need `-C`?

The problem is that that impacts users: what if I'm running a Scala script with `scala` and it takes a `--jvm` flag?  If I don't keep the current setup: `"${coursier_args[@]}" -- "${residual_args[@]}"` then we run the risk of user-level args/options being unexpectedly interpreted by coursier.

Actually, I wonder if this setup with Coursier has already burnt the user-level usage of `--`: as a user can I create a script that makes use of `--` and call it with `cs launch myapp -- foo -- foo/bar.txt`?

**Comment by dwijnand** [comment]
> Yeah, but I feel like it's better to build less and expose composable bits, instead of "magic-ing it away"

I still feel this is the right call.  It's akin to sbt and zinc wrapping the compiler and trying to magic away details...  It's only work up to the second you doubt it and/or need to tweak it - then you need to know what it's doing exactly and need to get involved directly.

It's one of the reasons that sbt-extras has a `-v` flag, as does scala-runners.  It's also similar to -Ylog-classpath which shows you all the pieces to the classpath puzzle, so you know what inputs you have and what values they had when the classpath was being composed.

For now (at least) let's not have a forwarder for `-C--jvm`.
