### ISSUE TITLE
Make it even easier to add library dependencies?

### ISSUE THREAD

**Issue by lrytz** [dwijnand/scala-runners#3]
This works:

```
~/scala/scala-runners/scala -cp $(coursier fetch -p com.chuusai:shapeless_2.13:2.3.3)
```

But it would be nicer with less boilerplate, something like `scala -dep com.chuusai:shapeless`. We know the binary version, coursier finds (right?) the latest dependency version.

Also, doing everything in one invocation of coursier would make it faster.

**Comment by dwijnand** [comment]
In the shell script wrapper (that is this project) we don't _exactly_ have the binary version.  With the -212, etc flags we do.  We'd have to switch from latest.stable to 2.13+ as the default in order to have a default binary version that matches.  But what do we do with `--scala-version 2.13.0-RC`?  Use 2.13 or the whole string?  What about 2.13.0-bin-<gitsha> or 2.14.0-pre-<gitsha>?

And still that wouldn't solve the number of invocations of coursier.  Because coursier launch wants to resolve scala-compiler and its transitive dependencies to run the repl main.  Separately the repl main can take a classpath of dependencies.. 

So it doesn't really fit into coursier's CLI APIs.  Perhaps the solution is a Graal native built coursier, called twice.  Or perhaps this project should become a Scala project and switch from Coursier's CLI API to its library API.

**Comment by dwijnand** [comment]
This is the alternative that we should the Graal native built solution to:

* Coursier's CLI API: https://get-coursier.io/docs/api.html
* overlay the command-line flags (like sbt-extras) to pull out scala-runner specific options, like `--dep` that runs Coursier to get dependencies that then feed into the classpath of the scala app (e.g. scalac, the scala repl. etc)
* then `sbt publishLocal` and `coursier bootstrap` from ~/.ivy2/local in the homebrew formula

**Comment by lrytz** [comment]
Given https://twitter.com/alxarchambault/status/1256195610031591424, this works:

```
➜ ~/Applications/bin/scala-runners/scala -Ccom.lihaoyi::fastparse:2.2.2
Welcome to Scala 2.13.2 (Java HotSpot(TM) 64-Bit GraalVM EE 19.2.1, Java 1.8.0_231).
Type in expressions for evaluation. Or try :help.

scala> import fastparse._, NoWhitespace._
import fastparse._
import NoWhitespace._
```

So we can close this, it's a matter of documentation.

**Comment by dwijnand** [comment]
f339bba851acd0c305f4e0d19fe22b9ed2f5d47d
